# Generated by Django 5.1.4 on 2025-01-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wera', '0007_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='wera',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
