# Generated by Django 5.1.5 on 2025-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wera", "0009_category_active_contact_active_location_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wera",
            name="application_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
