# Generated by Django 5.1.4 on 2025-01-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_mtaani", "0003_formmtaani_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formmtaani",
            options={"ordering": ["updated_at"]},
        ),
    ]
