# Generated by Django 5.1.5 on 2025-02-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_mtaani", "0004_alter_formmtaani_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="formmtaani",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
