# Generated by Django 5.1.4 on 2025-01-10 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_unique_together'),
        ('wera', '0005_alter_wera_options_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Profile',
        ),
    ]
