# Generated by Django 5.1.5 on 2025-02-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_alter_profile_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
