# Generated by Django 5.1.5 on 2025-02-16 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0008_profile_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
