# Generated by Django 5.1.5 on 2025-02-16 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0009_profile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
