# Generated by Django 5.1.4 on 2025-01-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0002_contactme_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMe',
        ),
    ]
